version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: realdb-postgres
    restart: always
    environment:
      POSTGRES_DB: realdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TowardsWeGo@40
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ideatoreality-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/realdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: TowardsWeGo@40

volumes:
  postgres_data:
  pgadmin_data:
